# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.7.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: venkyktmkid@gmail.com
author_name: K DHANU VENKATESH
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: OX-contracts

